name: CI/CD Kind Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t soham444/wisecow:latest .

    - name: Install Kind manually
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create Kind cluster
      run: kind create cluster --name kind --config kind-config.yaml

    - name: Load Docker image into Kind
      run: kind load docker-image soham444/wisecow:latest --name kind

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.0

    - name: Create Namespace
      run: kubectl create namespace wisecow || true

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s/manifests/ -n wisecow

    - name: Wait for Deployment to be ready
      run: kubectl wait --for=condition=available deployment/wisecow --namespace=wisecow --timeout=180s

    - name: Test Wisecow service inside cluster
      run: |
        kubectl run curlpod \
          --namespace=wisecow \
          --image=curlimages/curl \
          --restart=Never \
          --command -- curl --insecure https://wisecow:443
    

    - name: Get Wisecow pods and service info
      run: |
        echo "Pods in wisecow namespace:"
        kubectl get pods -n wisecow
        echo "Services in wisecow namespace:"
        kubectl get svc -n wisecow
        echo "Ingress in wisecow namespace:"
        kubectl get ingress -n wisecow

